=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" minOccurs="3" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo" type="xs:string"/>
                        <xs:element name="autor" type="xs:string"/>
                        <xs:element name="anio_publicacion" type="xs:integer"/>
                        <xs:element name="editorial" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="biblioteca.xsd">
    
 <libro>
        <titulo>
            Sombras de invierno</titulo>
        <autor>
            Neil Gaiman</autor>
        <anio_publicacion>
            2022
        </anio_publicacion>
        <editorial>
            Minotauro</editorial>
    </libro>

    <libro>
        <titulo>
            Horizonte perdido
        </titulo>
        <autor>
            Haruki Murakami
        </autor>
        <anio_publicacion>
            2024
        </anio_publicacion>
    </libro>

    <libro>
        <titulo>
            La melodia de los secretos</titulo>
        <autor>
            Isabel Allende</autor>
        <anio_publicacion>
            2023
        </anio_publicacion>
        <editorial>
            Montena</editorial>
    </libro>

</biblioteca>
