=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/catalogo.dtd
<!ELEMENT catalogo (producto+)>
    <!ELEMENT producto (nombre,marca,categoria,precio,descripcion?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT categoria (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ATTLIST producto id ID #REQUIRED>
    <!ATTLIST producto en_oferta CDATA #FIXED "si">
    <!ATTLIST precio moneda CDATA "EUR">

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
    <producto id="A">
        <nombre>AirPods Pro 3</nombre>
        <marca>Apple</marca>
        <categoria>Accesorio</categoria>
        <precio moneda="EUR">249</precio>
        <descripcion>Diseniado para todos los grupos de edad</descripcion>
    </producto>

    <producto id="B" en_oferta="si">
        <nombre>OPPO Reno 14</nombre>
        <marca>OPPO</marca>
        <categoria>Smartphone</categoria>
        <precio moneda="EUR">469</precio>
    </producto>

    <producto id="C">
        <nombre>Lenovo IdeaPad Slim 3</nombre>
        <marca>Lenovo</marca>
        <categoria>Portatil</categoria>
        <precio>749</precio>
    </producto>
    
</catalogo>
