=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/cinee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="genero" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="director"/>
                            <xs:element name="valoracion">
                                <xs:complexType>
                                    <xs:attribute name="nota" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="reparto">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="interprete" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="estreno" type="xs:integer" use="required"/>
                        <xs:attribute name="minutos" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="genero">
        <xs:restriction base="xs:string">
            <xs:enumeration value="drama"/>
            <xs:enumeration value="comedia"/>
            <xs:enumeration value="fantasia"/>
            <xs:enumeration value="documental"/>
            <xs:enumeration value="historia"/>
            <xs:enumeration value="guerra"/>
            <xs:enumeration value="western"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nota">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="estreno">
        <xs:restriction base="xs:string">
            <xs:pattern value="19\d\d"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="director">
        <xs:restriction base="xs:string">
            <xs:maxLength value="15"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/cinee.xml
<?xml version="1.0" encoding="UTF-8"?>
<cine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cinee.xsd">
    <pelicula estreno="1942" minutos="102">
        <titulo genero="drama">Casablanca</titulo>
        <director>Michael Curtiz</director>
        <valoracion nota="5"/>
        <reparto>
            <interprete>Humphrey Bogart</interprete>
            <interprete>Ingrid Bergman</interprete>
            <interprete>Paul Henreid</interprete>
            <interprete>Claude Rains</interprete>
            <interprete>Conrad Veidt</interprete>
            <interprete>Curt Bois</interprete>
        </reparto>
    </pelicula>
</cine>
