=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/especies.dtd
<!ELEMENT especies (especie+)>
<!ELEMENT especie (nombre, familia, areas)>
<!ATTLIST especie estado (extinguido | amenazado | sin-peligro) #REQUIRED 
identificador ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre nombre-cientifico CDATA #REQUIRED>
<!ELEMENT familia (#PCDATA)>
<!ELEMENT areas (zona+)>
<!ELEMENT zona (#PCDATA)>

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/especies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE especies SYSTEM "especies.dtd">
<especies>
    <especie estado="amenazado" identificador="es1">
        <nombre nombre-cientifico="Panthera leo">León</nombre>
        <familia>Felidae</familia>
        <areas>
            <zona>África subsahariana</zona>
            <zona>India</zona>
        </areas>
    </especie>

    <especie estado="sin-peligro" identificador="es2">
        <nombre nombre-cientifico="Canis lupus">Lobo</nombre>
        <familia>Canidae</familia>
        <areas>
            <zona>Europa</zona>
        </areas>
    </especie>
</especies>
