=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/facturas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="facturas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="factura"  minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha_emision" type="xs:date"/>
                            <xs:element name="empresa_emisora" type="xs:string"/>
                            <xs:element name="importe_total">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.01"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="iva">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id_factura" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="FACT-[0-9]{5}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="metodo_pago" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="tarjeta"/>
                                    <xs:enumeration value="transferencia"/>
                                    <xs:enumeration value="efectivo"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="pagada" type="xs:boolean" use="optional" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<facturas
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="facturas.xsd">

    <factura id_factura="FACT-00123" metodo_pago="tarjeta" pagada="true">
        <fecha_emision>2025-10-14</fecha_emision>
        <empresa_emisora>PcBox.</empresa_emisora>
        <importe_total>350.75</importe_total>
        <iva>21</iva>
    </factura>

    <factura id_factura="FACT-00124" metodo_pago="efectivo">
        <fecha_emision>2025-10-15</fecha_emision>
        <empresa_emisora>Amazon</empresa_emisora>
        <importe_total>1200.00</importe_total>
        <iva>10</iva>
    </factura>

</facturas>
