=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:date"/>
                            <xs:element name="cliente" type="xs:string"/>
                            <xs:element name="total_pedido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.01"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id_pedido" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="PED-[0-9]{4}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="estado" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="procesando"/>
                                    <xs:enumeration value="enviado"/>
                                    <xs:enumeration value="entregado"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="urgente" type="xs:boolean" use="optional" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ikervallss35/EjerciciosLenguajeDeMarcasIkerValls1DAW/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="pedidos.xsd">

    <pedido id_pedido="PED-1234" estado="procesando" urgente="true"> 
        <fecha>2025-10-13</fecha>
    <cliente>Arturo Guerrero</cliente>
    <total_pedido>149.99</total_pedido>
</pedido>

<pedido id_pedido="PED-1235" estado="enviado"> 
        <fecha>2025-10-13</fecha>
    <cliente>Lucas Garcia</cliente>
    <total_pedido>200.00</total_pedido>
</pedido>
</pedidos>
